apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: cloud-demo456
  namespace: feike
spec:
  teamId: "ClOuD"
  dockerImage: 142548018081.dkr.ecr.us-east-2.amazonaws.com/patroni:0.0.6
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    # database owner
    zalando:
    - superuser
    - createdb

    # role for application foo
    foo_user: []

  databases:
    foo: zalando
  postgresql:
    version: "11"
    parameters:
      # The postgres operator/spilo logs to csv files per weekday by default
      logging_collector: 'off'
      shared_preload_libraries: pg_stat_statements,timescaledb,auto_explain
      # We want to have these extensions available to all our connections, but
      # we disable them by default to reduce overhead
      "pg_stat_statements.track": "none"
      "auto_explain.log_min_duration": "-1"

